data:
  dataset: "celeba"
  root: "/data/celeba"
  from_hub: true  # run "modal run modal_app.py --action download" first, huggingface will use the arrow files that you pre-download afterwards
  repo_name: "electronickale/cmu-10799-celeba64-subset"
  image_size: 64
  channels: 3
  num_workers: 4
  pin_memory: true
  augment: true

# TODO: build your model architecture, feel free to add or exclude any of these options
model:
  base_channels: 64
  channel_mult: [1, 2, 2, 4]
  num_res_blocks: 2
  attention_resolutions: [16, 8]
  num_heads: 4
  dropout: 0.1
  use_scale_shift_norm: true

# TODO: your training hyperparameters, feel free to add or exclude any of these options
training:
  batch_size: 128
  learning_rate: 2.0e-4
  weight_decay: 0.0
  betas: [0.9, 0.999]
  ema_decay: 0.9999
  ema_start: 1000 # start using EMA for sampling after this step
  gradient_clip_norm: 1.0
  num_iterations: 120000
  log_every: 100
  sample_every: 4000
  save_every: 4000
  num_samples: 16

# TODO: your ddpm algorithm hyperparameters, feel free to add or exclude any of these options
ddpm:
  num_timesteps: 1000
  beta_start: 1.0e-4
  beta_end: 2.0e-2
  #parameterization: x0
  parameterization: eps

sampling:
  num_steps: 100
  sampler: "ddim"

infrastructure:
  seed: 42
  device: "cuda"
  num_gpus: 1
  mixed_precision: true
  compile_model: false # only tested false

checkpoint:
  dir: "./checkpoints"
  resume: null

logging:
  dir: "./logs"
  wandb:
    enabled: true
    project: "cmu-10799-diffusion"
    entity: null

